"""Protocolos (interfaces) dos repositórios — sem dependência de SQLite ou qualquer storage."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from canal_soberania.models import Clip, ClipStatus, Video, VideoStatus


@runtime_checkable
class VideoRepository(Protocol):
    def get(self, video_id: str) -> Video | None: ...
    def get_all(self) -> list[Video]: ...
    def get_by_status(self, status: VideoStatus) -> list[Video]: ...
    def status_summary(self) -> dict[str, int]: ...
    def monthly_cost(self) -> float: ...


@runtime_checkable
class ClipRepository(Protocol):
    def get(self, clip_id: str) -> Clip | None: ...
    def get_all(self) -> list[Clip]: ...
    def get_by_status(self, status: ClipStatus) -> list[Clip]: ...
