"""Protocolos (interfaces) dos repositórios — sem dependência de SQLite ou qualquer storage."""

from __future__ import annotations

from typing import Literal, Protocol, runtime_checkable

from canal_soberania.models import Clip, ClipStatus, Video, VideoStatus


@runtime_checkable
class VideoRepository(Protocol):
    def get(self, video_id: str) -> Video | None: ...
    def get_all(self) -> list[Video]: ...
    def get_by_status(self, status: VideoStatus) -> list[Video]: ...
    def status_summary(self) -> dict[str, int]: ...
    def monthly_cost(self) -> float: ...
    def update_status(self, video_id: str, new_status: str) -> None: ...
    def reject(self, video_id: str) -> None: ...
    def reset_stuck(self, stuck_configs: list[tuple[str, str]]) -> int: ...


@runtime_checkable
class ClipRepository(Protocol):
    def get(self, clip_id: str) -> Clip | None: ...
    def get_all(self) -> list[Clip]: ...
    def get_by_status(self, status: ClipStatus) -> list[Clip]: ...
    def update_text(
        self,
        clip_id: str,
        hook: str | None,
        payoff: str | None,
        title: str | None,
        youtube_publish_at: str | None,
        render_vertical: bool = True,
        render_horizontal: bool = True,
    ) -> None: ...
    def update_metadata_fields(
        self,
        clip_id: str,
        *,
        hook: str | None = None,
        payoff: str | None = None,
        title: str | None = None,
        description: str | None = None,
        tags: list[str] | None = None,
        youtube_publish_at: str | None = None,
        render_vertical: bool | None = None,
        render_horizontal: bool | None = None,
        score_viral: int | None = None,
    ) -> None: ...
    def clear_platform_id(
        self, clip_id: str, *, kind: Literal["vertical", "horizontal"]
    ) -> None: ...
    def update_status(self, clip_id: str, new_status: str) -> None: ...
    def reject(self, clip_id: str, reason: str) -> None: ...
    def restore(self, clip_id: str) -> None: ...
    def update_trim(self, clip_id: str, start_s: float, end_s: float) -> None: ...
    def reset_stuck(self, stuck_configs: list[tuple[str, str]]) -> int: ...
    def delete(self, clip_id: str) -> None: ...
